export type UserRole = "ADMIN" | "AGENT" | "UNDERWRITER" | "CLAIMS_OFFICER" | "CUSTOMER";

export type AuditEvent =
  | "USER_LOGIN"
  | "USER_REGISTERED"
  | "POLICY_ISSUED"
  | "POLICY_CANCELLED"
  | "POLICY_RENEWED"
  | "CLAIM_SUBMITTED"
  | "CLAIM_APPROVED"
  | "CLAIM_REJECTED"
  | "PAYMENT_RECORDED";
